### ISSUE TITLE
Installed but not available

### ISSUE THREAD

**Issue by fr32c** [davidderaedt/Illustrator-Layer-Exporter#1] opened 2013-09-14 09:59 UTC
I restarted Illustrator. The extension is seen as installed, but not available in the window menu.

![installationlayerexchange](https://f.cloud.github.com/assets/2315207/1143189/4171c3c2-1d24-11e3-8ab5-27af46173bfd.png)

I received an authentify request from ExManCmd, was told it was installed, but not available to find it. Maybe language issue (shown as EN when my OS and Ai are FR…)

-- edit après install --
On Retina MBPro (10.8), extension installed silently and is shown where expected. It isn't a FR vs EN issue.

**Comment by fr32c** [comment] 2013-09-16 09:41
As recommended I tried to install it from http://davidderaedt.github.io/AILayerExporterPage/ directly from the zxp, rather than Extension Manager, no more success.

**Comment by davidderaedt** [comment] 2014-04-09 09:29
Original issue is duplicate of #6, second one is fixed.

**Closed as completed by davidderaedt** 2014-04-09 09:29 UTC
